server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: content-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qwerty}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:LmAxBynYUYDh9uLxzGYCHCGSIVceE2E87aLSRtVVgAGxLlHtbz6Hn3TMP4DwYfPyjEfwUlKopDnLKnB4UpTexV}

learning:
  service:
    url: ${LEARNING_SERVICE_URL:http://localhost:8083}

ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
